'use client';

import { useState, useEffect } from 'react';
import { 
  History,
  CheckCircle,
  XCircle,
  Ban,
  Loader2,
  AlertCircle,
  Image,
  Video,
  FileText,
  Link as LinkIcon,
  Clock,
  ChevronLeft,
  ChevronRight
} from 'lucide-react';
import { format } from 'date-fns';
import { toZonedTime } from 'date-fns-tz';

const NY_TIMEZONE = 'America/New_York';

interface HistoryPost {
  _id: string;
  contentType: string;
  message: string;
  mediaUrl?: string;
  link?: string;
  templateName?: string;
  scheduledAt: string;
  sentAt?: string;
  status: 'sent' | 'failed' | 'cancelled';
  errorMessage?: string;
  isAutoGenerated: boolean;
}

interface HistoryTabProps {
  entityId: string;
}

interface Stats {
  sent: number;
  failed: number;
  cancelled: number;
  total: number;
}

export default function HistoryTab({ entityId }: HistoryTabProps) {
  const [posts, setPosts] = useState<HistoryPost[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [stats, setStats] = useState<Stats>({ sent: 0, failed: 0, cancelled: 0, total: 0 });
  const [statusFilter, setStatusFilter] = useState<string>('');

  useEffect(() => {
    fetchHistory();
  }, [entityId, page, statusFilter]);

  const fetchHistory = async () => {
    setIsLoading(true);
    setError('');
    try {
      const params = new URLSearchParams({
        page: page.toString(),
        limit: '10',
      });
      if (statusFilter) {
        params.set('status', statusFilter);
      }
      
      const res = await fetch(`/api/entities/${entityId}/history?${params}`);
      if (!res.ok) throw new Error('Failed to fetch history');
      const data = await res.json();
      setPosts(data.posts || []);
      setTotalPages(data.pagination?.totalPages || 1);
      setStats(data.stats || { sent: 0, failed: 0, cancelled: 0, total: 0 });
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load history');
    } finally {
      setIsLoading(false);
    }
  };

  const formatDate = (date: string) => {
    const dateInNY = toZonedTime(new Date(date), NY_TIMEZONE);
    return format(dateInNY, 'MMM d, yyyy h:mm a');
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'sent':
        return <CheckCircle size={16} className="text-green-500" />;
      case 'failed':
        return <XCircle size={16} className="text-red-500" />;
      case 'cancelled':
        return <Ban size={16} className="text-gray-500" />;
      default:
        return <Clock size={16} className="text-gray-400" />;
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'sent':
        return 'bg-green-100 text-green-700';
      case 'failed':
        return 'bg-red-100 text-red-700';
      case 'cancelled':
        return 'bg-gray-100 text-gray-700';
      default:
        return 'bg-gray-100 text-gray-600';
    }
  };

  const getContentTypeIcon = (type: string) => {
    switch (type) {
      case 'image':
        return <Image size={14} className="text-blue-500" />;
      case 'video':
        return <Video size={14} className="text-purple-500" />;
      case 'youtube':
      case 'podcast':
      case 'article':
        return <LinkIcon size={14} className="text-orange-500" />;
      default:
        return <FileText size={14} className="text-gray-500" />;
    }
  };

  if (isLoading && posts.length === 0) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="w-8 h-8 animate-spin text-whatsapp-green" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-2xl p-6 text-center">
        <AlertCircle className="w-8 h-8 mx-auto text-red-500 mb-2" />
        <p className="text-red-600">{error}</p>
        <button
          onClick={fetchHistory}
          className="mt-4 px-4 py-2 bg-red-100 text-red-700 rounded-lg hover:bg-red-200 transition-colors"
        >
          Try Again
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Stats Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div 
          onClick={() => setStatusFilter('')}
          className={`bg-white border rounded-xl p-4 cursor-pointer transition-all ${
            statusFilter === '' ? 'border-whatsapp-green ring-2 ring-whatsapp-green/20' : 'border-gray-200 hover:border-gray-300'
          }`}
        >
          <div className="flex items-center gap-2 mb-1">
            <History size={16} className="text-gray-500" />
            <span className="text-xs font-medium text-gray-500 uppercase">Total</span>
          </div>
          <p className="text-2xl font-semibold text-gray-900">{stats.total}</p>
        </div>
        
        <div 
          onClick={() => setStatusFilter('sent')}
          className={`bg-white border rounded-xl p-4 cursor-pointer transition-all ${
            statusFilter === 'sent' ? 'border-green-500 ring-2 ring-green-500/20' : 'border-gray-200 hover:border-gray-300'
          }`}
        >
          <div className="flex items-center gap-2 mb-1">
            <CheckCircle size={16} className="text-green-500" />
            <span className="text-xs font-medium text-gray-500 uppercase">Sent</span>
          </div>
          <p className="text-2xl font-semibold text-green-600">{stats.sent}</p>
        </div>
        
        <div 
          onClick={() => setStatusFilter('failed')}
          className={`bg-white border rounded-xl p-4 cursor-pointer transition-all ${
            statusFilter === 'failed' ? 'border-red-500 ring-2 ring-red-500/20' : 'border-gray-200 hover:border-gray-300'
          }`}
        >
          <div className="flex items-center gap-2 mb-1">
            <XCircle size={16} className="text-red-500" />
            <span className="text-xs font-medium text-gray-500 uppercase">Failed</span>
          </div>
          <p className="text-2xl font-semibold text-red-600">{stats.failed}</p>
        </div>
        
        <div 
          onClick={() => setStatusFilter('cancelled')}
          className={`bg-white border rounded-xl p-4 cursor-pointer transition-all ${
            statusFilter === 'cancelled' ? 'border-gray-500 ring-2 ring-gray-500/20' : 'border-gray-200 hover:border-gray-300'
          }`}
        >
          <div className="flex items-center gap-2 mb-1">
            <Ban size={16} className="text-gray-500" />
            <span className="text-xs font-medium text-gray-500 uppercase">Cancelled</span>
          </div>
          <p className="text-2xl font-semibold text-gray-600">{stats.cancelled}</p>
        </div>
      </div>

      {/* Posts List */}
      {posts.length === 0 ? (
        <div className="bg-white border border-gray-200 rounded-2xl p-12 text-center">
          <History size={48} className="mx-auto text-gray-400 mb-4" />
          <h3 className="text-lg font-medium text-gray-900 mb-2">No history yet</h3>
          <p className="text-gray-600">
            {statusFilter 
              ? `No ${statusFilter} posts found for this entity.`
              : 'Posts that have been sent, failed, or cancelled will appear here.'
            }
          </p>
        </div>
      ) : (
        <div className="bg-white border border-gray-200 rounded-2xl overflow-hidden">
          <div className="divide-y divide-gray-100">
            {posts.map((post) => (
              <div key={post._id} className="p-4 hover:bg-gray-50 transition-colors">
                <div className="flex items-start gap-4">
                  {/* Status Icon */}
                  <div className="mt-1">
                    {getStatusIcon(post.status)}
                  </div>
                  
                  {/* Content */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${getStatusBadge(post.status)}`}>
                        {post.status.charAt(0).toUpperCase() + post.status.slice(1)}
                      </span>
                      <span className="flex items-center gap-1 text-xs text-gray-500">
                        {getContentTypeIcon(post.contentType)}
                        {post.contentType}
                      </span>
                      {post.templateName && (
                        <span className="text-xs text-gray-400">
                          • {post.templateName}
                        </span>
                      )}
                      {post.isAutoGenerated && (
                        <span className="text-xs bg-blue-100 text-blue-700 px-1.5 py-0.5 rounded">
                          Auto
                        </span>
                      )}
                    </div>
                    
                    {/* Message Preview */}
                    <p className="text-sm text-gray-700 line-clamp-2 mb-2">
                      {post.message}
                    </p>
                    
                    {/* Error Message if failed */}
                    {post.status === 'failed' && post.errorMessage && (
                      <p className="text-xs text-red-600 bg-red-50 p-2 rounded mb-2">
                        Error: {post.errorMessage}
                      </p>
                    )}
                    
                    {/* Timestamps */}
                    <div className="flex items-center gap-4 text-xs text-gray-500">
                      <span>Scheduled: {formatDate(post.scheduledAt)}</span>
                      {post.sentAt && (
                        <span>Sent: {formatDate(post.sentAt)}</span>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
          
          {/* Pagination */}
          {totalPages > 1 && (
            <div className="flex items-center justify-between px-4 py-3 border-t border-gray-100 bg-gray-50">
              <p className="text-sm text-gray-600">
                Page {page} of {totalPages}
              </p>
              <div className="flex gap-2">
                <button
                  onClick={() => setPage(p => Math.max(1, p - 1))}
                  disabled={page === 1}
                  className="p-2 border border-gray-200 rounded-lg hover:bg-white disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                >
                  <ChevronLeft size={16} />
                </button>
                <button
                  onClick={() => setPage(p => Math.min(totalPages, p + 1))}
                  disabled={page === totalPages}
                  className="p-2 border border-gray-200 rounded-lg hover:bg-white disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                >
                  <ChevronRight size={16} />
                </button>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

