'use client';

import { useState, useEffect } from 'react';
import { 
  Clock,
  CheckCircle,
  XCircle,
  Loader2,
  AlertCircle,
  Image,
  Video,
  FileText,
  Link as LinkIcon,
  Trash2,
  ChevronLeft,
  ChevronRight,
  RefreshCw
} from 'lucide-react';
import { format } from 'date-fns';
import { toZonedTime } from 'date-fns-tz';

const NY_TIMEZONE = 'America/New_York';

interface ScheduledPost {
  _id: string;
  contentType: string;
  message: string;
  mediaUrl?: string;
  link?: string;
  templateName?: string;
  scheduledAt: string;
  status: 'scheduled' | 'processing' | 'sent' | 'failed' | 'cancelled';
  isAutoGenerated: boolean;
}

interface ScheduledPostsTabProps {
  entityId: string;
}

export default function ScheduledPostsTab({ entityId }: ScheduledPostsTabProps) {
  const [posts, setPosts] = useState<ScheduledPost[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [total, setTotal] = useState(0);
  
  const [deleteConfirmId, setDeleteConfirmId] = useState<string | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);

  useEffect(() => {
    fetchScheduledPosts();
  }, [entityId, page]);

  const fetchScheduledPosts = async () => {
    setIsLoading(true);
    setError('');
    try {
      const params = new URLSearchParams({
        entityId,
        status: 'scheduled',
        page: page.toString(),
        limit: '10',
      });
      
      const res = await fetch(`/api/posts?${params}`);
      if (!res.ok) throw new Error('Failed to fetch scheduled posts');
      const data = await res.json();
      setPosts(data.posts || []);
      setTotalPages(data.pagination?.totalPages || 1);
      setTotal(data.pagination?.total || 0);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load scheduled posts');
    } finally {
      setIsLoading(false);
    }
  };

  const formatDate = (date: string) => {
    const dateInNY = toZonedTime(new Date(date), NY_TIMEZONE);
    return format(dateInNY, 'MMM d, yyyy h:mm a');
  };

  const canDelete = (post: ScheduledPost) => {
    if (post.status !== 'scheduled') return false;
    const now = new Date();
    const scheduledTime = new Date(post.scheduledAt);
    return scheduledTime > now;
  };

  const getTimeUntil = (date: string) => {
    const now = new Date();
    const scheduledTime = new Date(date);
    const diff = scheduledTime.getTime() - now.getTime();
    
    if (diff <= 0) return 'Due now';
    
    const minutes = Math.floor(diff / (1000 * 60));
    const hours = Math.floor(minutes / 60);
    const days = Math.floor(hours / 24);
    
    if (days > 0) return `in ${days}d ${hours % 24}h`;
    if (hours > 0) return `in ${hours}h ${minutes % 60}m`;
    return `in ${minutes}m`;
  };

  const getContentTypeIcon = (type: string) => {
    switch (type) {
      case 'image':
        return <Image size={14} className="text-blue-500" />;
      case 'video':
        return <Video size={14} className="text-purple-500" />;
      case 'youtube':
      case 'podcast':
      case 'article':
        return <LinkIcon size={14} className="text-orange-500" />;
      default:
        return <FileText size={14} className="text-gray-500" />;
    }
  };

  const handleDelete = async (postId: string) => {
    setIsDeleting(true);
    try {
      const res = await fetch(`/api/posts/${postId}`, {
        method: 'DELETE',
      });
      
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || 'Failed to delete');
      }
      
      // Remove from local state
      setPosts(prev => prev.filter(p => p._id !== postId));
      setTotal(prev => prev - 1);
      setDeleteConfirmId(null);
    } catch (err) {
      alert(err instanceof Error ? err.message : 'Failed to delete post');
    } finally {
      setIsDeleting(false);
    }
  };

  if (isLoading && posts.length === 0) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="w-8 h-8 animate-spin text-whatsapp-green" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-2xl p-6 text-center">
        <AlertCircle className="w-8 h-8 mx-auto text-red-500 mb-2" />
        <p className="text-red-600">{error}</p>
        <button
          onClick={fetchScheduledPosts}
          className="mt-4 px-4 py-2 bg-red-100 text-red-700 rounded-lg hover:bg-red-200 transition-colors"
        >
          Try Again
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-semibold text-whatsapp-dark-teal">Scheduled Posts</h3>
          <p className="text-sm text-gray-600">{total} posts scheduled</p>
        </div>
        <button
          onClick={fetchScheduledPosts}
          disabled={isLoading}
          className="flex items-center gap-2 px-3 py-2 text-sm border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors disabled:opacity-50"
        >
          <RefreshCw size={16} className={isLoading ? 'animate-spin' : ''} />
          Refresh
        </button>
      </div>

      {/* Posts List */}
      {posts.length === 0 ? (
        <div className="bg-white border border-gray-200 rounded-2xl p-12 text-center">
          <Clock size={48} className="mx-auto text-gray-400 mb-4" />
          <h3 className="text-lg font-medium text-gray-900 mb-2">No scheduled posts</h3>
          <p className="text-gray-600">
            Schedule posts from the Entities page or use auto-generate.
          </p>
        </div>
      ) : (
        <div className="bg-white border border-gray-200 rounded-2xl overflow-hidden">
          <div className="divide-y divide-gray-100">
            {posts.map((post) => {
              const deletable = canDelete(post);
              
              return (
                <div key={post._id} className="p-4 hover:bg-gray-50 transition-colors">
                  <div className="flex items-start gap-4">
                    {/* Status Icon */}
                    <div className="mt-1">
                      <Clock size={16} className="text-blue-500" />
                    </div>
                    
                    {/* Content */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <span className="px-2 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-700">
                          Scheduled
                        </span>
                        <span className="flex items-center gap-1 text-xs text-gray-500">
                          {getContentTypeIcon(post.contentType)}
                          {post.contentType}
                        </span>
                        {post.templateName && (
                          <span className="text-xs text-gray-400">
                            • {post.templateName}
                          </span>
                        )}
                        {post.isAutoGenerated && (
                          <span className="text-xs bg-purple-100 text-purple-700 px-1.5 py-0.5 rounded">
                            Auto
                          </span>
                        )}
                      </div>
                      
                      {/* Message Preview */}
                      <p className="text-sm text-gray-700 line-clamp-2 mb-2">
                        {post.message}
                      </p>
                      
                      {/* Timestamps */}
                      <div className="flex items-center gap-4 text-xs text-gray-500">
                        <span>📅 {formatDate(post.scheduledAt)}</span>
                        <span className="text-blue-600 font-medium">
                          ⏰ {getTimeUntil(post.scheduledAt)}
                        </span>
                      </div>
                    </div>
                    
                    {/* Delete Button */}
                    <button
                      onClick={() => setDeleteConfirmId(post._id)}
                      disabled={!deletable}
                      className={`p-2 rounded-lg transition-colors ${
                        deletable
                          ? 'text-gray-400 hover:text-red-500 hover:bg-red-50'
                          : 'text-gray-300 cursor-not-allowed'
                      }`}
                      title={deletable ? 'Delete post' : 'Cannot delete after scheduled time'}
                    >
                      <Trash2 size={18} />
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
          
          {/* Pagination */}
          {totalPages > 1 && (
            <div className="flex items-center justify-between px-4 py-3 border-t border-gray-100 bg-gray-50">
              <p className="text-sm text-gray-600">
                Page {page} of {totalPages}
              </p>
              <div className="flex gap-2">
                <button
                  onClick={() => setPage(p => Math.max(1, p - 1))}
                  disabled={page === 1}
                  className="p-2 border border-gray-200 rounded-lg hover:bg-white disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                >
                  <ChevronLeft size={16} />
                </button>
                <button
                  onClick={() => setPage(p => Math.min(totalPages, p + 1))}
                  disabled={page === totalPages}
                  className="p-2 border border-gray-200 rounded-lg hover:bg-white disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                >
                  <ChevronRight size={16} />
                </button>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {deleteConfirmId && (
        <div 
          className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"
          onClick={() => setDeleteConfirmId(null)}
        >
          <div 
            className="bg-white rounded-2xl p-6 max-w-sm w-full shadow-xl"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="text-center">
              <div className="w-12 h-12 rounded-full bg-red-100 flex items-center justify-center mx-auto mb-4">
                <Trash2 size={24} className="text-red-600" />
              </div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">Delete Scheduled Post?</h3>
              <p className="text-gray-600 mb-6">
                This will permanently delete this scheduled post. This action cannot be undone.
              </p>
              <div className="flex gap-3">
                <button
                  onClick={() => setDeleteConfirmId(null)}
                  disabled={isDeleting}
                  className="flex-1 px-4 py-2 border border-gray-200 text-gray-700 rounded-lg font-medium hover:bg-gray-50 transition-colors disabled:opacity-50"
                >
                  Cancel
                </button>
                <button
                  onClick={() => handleDelete(deleteConfirmId)}
                  disabled={isDeleting}
                  className="flex-1 px-4 py-2 bg-red-600 text-white rounded-lg font-medium hover:bg-red-700 transition-colors disabled:opacity-50"
                >
                  {isDeleting ? 'Deleting...' : 'Delete'}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

