'use client';

import { useState, useEffect } from 'react';
import { History, CheckCircle, XCircle, Clock, AlertCircle, RefreshCw, FileText, Image, Video, Link as LinkIcon, ChevronDown, ChevronUp, Trash2 } from 'lucide-react';
import { format } from 'date-fns';

interface Post {
  _id: string;
  entityId: string;
  contentType: string;
  message: string;
  mediaUrl?: string;
  link?: string;
  scheduledAt: string;
  status: 'scheduled' | 'processing' | 'sent' | 'failed' | 'cancelled';
  sentAt?: string;
  errorMessage?: string;
  isAutoGenerated: boolean;
  entity?: {
    companyName: string;
    tickerSymbol: string;
  };
  templateName?: string;
}

interface PostHistoryEntry {
  _id: string;
  entityId: string;
  contentType: string;
  message: string;
  mediaUrl?: string;
  sentAt: string;
  maytapiMessageId: string;
  entity?: {
    companyName: string;
    tickerSymbol: string;
  };
}

export default function HistoryPage() {
  const [posts, setPosts] = useState<Post[]>([]);
  const [history, setHistory] = useState<PostHistoryEntry[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<'scheduled' | 'sent' | 'failed'>('scheduled');
  const [expandedPost, setExpandedPost] = useState<string | null>(null);
  
  // Delete state
  const [deleteConfirmId, setDeleteConfirmId] = useState<string | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    setIsLoading(true);
    try {
      // Fetch scheduled posts
      const postsRes = await fetch('/api/posts?limit=100');
      const postsData = await postsRes.json();
      setPosts(postsData.posts || []);

      // Fetch post history
      const historyRes = await fetch('/api/history');
      const historyData = await historyRes.json();
      setHistory(historyData.history || []);
    } catch (error) {
      console.error('Failed to fetch data:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'sent': return <CheckCircle size={16} className="text-green-500" />;
      case 'failed': return <XCircle size={16} className="text-red-500" />;
      case 'scheduled': return <Clock size={16} className="text-blue-500" />;
      case 'processing': return <RefreshCw size={16} className="text-amber-500 animate-spin" />;
      case 'cancelled': return <XCircle size={16} className="text-gray-400" />;
      default: return <AlertCircle size={16} className="text-gray-400" />;
    }
  };

  const getStatusBadge = (status: string) => {
    const styles: Record<string, string> = {
      sent: 'bg-green-100 text-green-700',
      failed: 'bg-red-100 text-red-700',
      scheduled: 'bg-blue-100 text-blue-700',
      processing: 'bg-amber-100 text-amber-700',
      cancelled: 'bg-gray-100 text-gray-600',
    };
    return styles[status] || 'bg-gray-100 text-gray-600';
  };

  const getContentIcon = (type: string) => {
    switch (type) {
      case 'image': return <Image size={14} className="text-purple-500" />;
      case 'video': return <Video size={14} className="text-pink-500" />;
      case 'youtube':
      case 'podcast':
      case 'article':
      case 'link': return <LinkIcon size={14} className="text-blue-500" />;
      default: return <FileText size={14} className="text-gray-500" />;
    }
  };

  // Check if a post can be deleted
  const canDelete = (post: Post) => {
    if (post.status !== 'scheduled') return false;
    const now = new Date();
    const scheduledTime = new Date(post.scheduledAt);
    return scheduledTime > now;
  };

  // Get time until scheduled
  const getTimeUntil = (date: string) => {
    const now = new Date();
    const scheduledTime = new Date(date);
    const diff = scheduledTime.getTime() - now.getTime();
    
    if (diff <= 0) return 'Due now';
    
    const minutes = Math.floor(diff / (1000 * 60));
    const hours = Math.floor(minutes / 60);
    const days = Math.floor(hours / 24);
    
    if (days > 0) return `in ${days}d ${hours % 24}h`;
    if (hours > 0) return `in ${hours}h ${minutes % 60}m`;
    return `in ${minutes}m`;
  };

  // Handle delete
  const handleDelete = async (postId: string) => {
    setIsDeleting(true);
    try {
      const res = await fetch(`/api/posts/${postId}`, {
        method: 'DELETE',
      });
      
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || 'Failed to delete');
      }
      
      // Remove from local state
      setPosts(prev => prev.filter(p => p._id !== postId));
      setDeleteConfirmId(null);
    } catch (err) {
      alert(err instanceof Error ? err.message : 'Failed to delete post');
    } finally {
      setIsDeleting(false);
    }
  };

  const scheduledPosts = posts.filter(p => p.status === 'scheduled' || p.status === 'processing');
  const sentPosts = posts.filter(p => p.status === 'sent');
  const failedPosts = posts.filter(p => p.status === 'failed');

  const getDisplayPosts = () => {
    switch (activeTab) {
      case 'scheduled': return scheduledPosts;
      case 'sent': return sentPosts;
      case 'failed': return failedPosts;
      default: return [];
    }
  };

  const toggleExpand = (postId: string) => {
    setExpandedPost(expandedPost === postId ? null : postId);
  };

  return (
    <div className="space-y-8">
      {/* Page header */}
      <header className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight text-whatsapp-dark-teal">
            Post History
          </h1>
          <p className="text-sm text-gray-600 mt-1">
            View scheduled, sent, and failed posts
          </p>
        </div>
        <button
          onClick={fetchData}
          disabled={isLoading}
          className="flex items-center gap-2 px-4 py-2 bg-whatsapp-green text-white rounded-lg font-medium hover:bg-whatsapp-teal transition-colors shadow-sm disabled:opacity-50"
        >
          <RefreshCw size={18} className={isLoading ? 'animate-spin' : ''} />
          Refresh
        </button>
      </header>

      {/* Stats Cards */}
      <div className="grid grid-cols-3 gap-4">
        <div className="bg-white border border-gray-200 rounded-xl p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-100 rounded-lg">
              <Clock size={20} className="text-blue-600" />
            </div>
            <div>
              <p className="text-2xl font-bold text-gray-900">{scheduledPosts.length}</p>
              <p className="text-sm text-gray-500">Scheduled</p>
            </div>
          </div>
        </div>
        <div className="bg-white border border-gray-200 rounded-xl p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-green-100 rounded-lg">
              <CheckCircle size={20} className="text-green-600" />
            </div>
            <div>
              <p className="text-2xl font-bold text-gray-900">{sentPosts.length}</p>
              <p className="text-sm text-gray-500">Sent</p>
            </div>
          </div>
        </div>
        <div className="bg-white border border-gray-200 rounded-xl p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-red-100 rounded-lg">
              <XCircle size={20} className="text-red-600" />
            </div>
            <div>
              <p className="text-2xl font-bold text-gray-900">{failedPosts.length}</p>
              <p className="text-sm text-gray-500">Failed</p>
            </div>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="border-b border-gray-200">
        <nav className="flex gap-4">
          {[
            { id: 'scheduled', label: 'Scheduled', count: scheduledPosts.length },
            { id: 'sent', label: 'Sent', count: sentPosts.length },
            { id: 'failed', label: 'Failed', count: failedPosts.length },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as typeof activeTab)}
              className={`pb-3 px-1 border-b-2 font-medium text-sm transition-colors ${
                activeTab === tab.id
                  ? 'border-whatsapp-green text-whatsapp-dark-teal'
                  : 'border-transparent text-gray-500 hover:text-gray-700'
              }`}
            >
              {tab.label}
              <span className={`ml-2 px-2 py-0.5 rounded-full text-xs ${
                activeTab === tab.id ? 'bg-whatsapp-light-green text-whatsapp-dark-teal' : 'bg-gray-100 text-gray-600'
              }`}>
                {tab.count}
              </span>
            </button>
          ))}
        </nav>
      </div>

      {/* Posts List */}
      <div className="space-y-3">
        {isLoading ? (
          <div className="text-center py-12 text-gray-500">Loading...</div>
        ) : getDisplayPosts().length === 0 ? (
          <div className="bg-white border border-gray-200 rounded-xl p-12 text-center">
            <History size={48} className="mx-auto text-gray-400 mb-4" />
            <h3 className="text-lg font-medium text-gray-900 mb-2">No {activeTab} posts</h3>
            <p className="text-gray-600">
              {activeTab === 'scheduled' && 'Schedule posts from the Entities page'}
              {activeTab === 'sent' && 'Posts will appear here after they are sent'}
              {activeTab === 'failed' && 'Failed posts will appear here'}
            </p>
          </div>
        ) : (
          getDisplayPosts().map((post) => {
            const deletable = canDelete(post);
            
            return (
              <div 
                key={post._id} 
                className="bg-white border border-gray-200 rounded-xl overflow-hidden hover:shadow-md transition-shadow"
              >
                {/* Post Header */}
                <div className="p-4">
                  <div className="flex items-center justify-between">
                    <div 
                      className="flex items-center gap-3 flex-1 cursor-pointer"
                      onClick={() => toggleExpand(post._id)}
                    >
                      {getStatusIcon(post.status)}
                      <div className="flex-1">
                        <div className="flex items-center gap-2">
                          <span className="font-medium text-gray-900">
                            {post.entity?.companyName || 'Unknown Entity'}
                          </span>
                          <span className="text-sm text-gray-500">
                            ({post.entity?.tickerSymbol || '---'})
                          </span>
                          {getContentIcon(post.contentType)}
                        </div>
                        <div className="flex items-center gap-3 text-sm text-gray-500 mt-1">
                          <span>
                            {post.status === 'sent' && post.sentAt
                              ? `Sent: ${format(new Date(post.sentAt), 'MMM d, yyyy h:mm a')}`
                              : `Scheduled: ${format(new Date(post.scheduledAt), 'MMM d, yyyy h:mm a')}`}
                          </span>
                          {post.status === 'scheduled' && (
                            <span className="text-blue-600 font-medium">
                              ⏰ {getTimeUntil(post.scheduledAt)}
                            </span>
                          )}
                          <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${getStatusBadge(post.status)}`}>
                            {post.status}
                          </span>
                          {post.isAutoGenerated ? (
                            <span className="text-xs bg-purple-100 text-purple-700 px-2 py-0.5 rounded-full">Auto</span>
                          ) : (
                            <span className="text-xs bg-blue-100 text-blue-700 px-2 py-0.5 rounded-full">Manual</span>
                          )}
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      {/* Delete button for scheduled posts */}
                      {activeTab === 'scheduled' && (
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            setDeleteConfirmId(post._id);
                          }}
                          disabled={!deletable}
                          className={`p-2 rounded-lg transition-colors ${
                            deletable
                              ? 'text-gray-400 hover:text-red-500 hover:bg-red-50'
                              : 'text-gray-300 cursor-not-allowed'
                          }`}
                          title={deletable ? 'Delete post' : 'Cannot delete after scheduled time'}
                        >
                          <Trash2 size={18} />
                        </button>
                      )}
                      <button
                        onClick={() => toggleExpand(post._id)}
                        className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
                      >
                        {expandedPost === post._id ? (
                          <ChevronUp size={20} className="text-gray-400" />
                        ) : (
                          <ChevronDown size={20} className="text-gray-400" />
                        )}
                      </button>
                    </div>
                  </div>
                </div>

                {/* Expanded Details */}
                {expandedPost === post._id && (
                  <div className="px-4 pb-4 pt-0 border-t border-gray-100">
                    <div className="mt-4 space-y-4">
                      {/* Message Preview */}
                      <div>
                        <label className="block text-xs font-medium text-gray-500 mb-1 uppercase">Message</label>
                        <div className="bg-gray-50 rounded-lg p-3 text-sm text-gray-700 whitespace-pre-wrap max-h-40 overflow-y-auto">
                          {post.message}
                        </div>
                      </div>

                      {/* Media/Link Info */}
                      {post.mediaUrl && (
                        <div>
                          <label className="block text-xs font-medium text-gray-500 mb-1 uppercase">Media URL</label>
                          <a 
                            href={post.mediaUrl} 
                            target="_blank" 
                            rel="noopener noreferrer"
                            className="text-sm text-whatsapp-teal hover:underline break-all"
                          >
                            {post.mediaUrl}
                          </a>
                        </div>
                      )}

                      {post.link && (
                        <div>
                          <label className="block text-xs font-medium text-gray-500 mb-1 uppercase">Link</label>
                          <a 
                            href={post.link} 
                            target="_blank" 
                            rel="noopener noreferrer"
                            className="text-sm text-whatsapp-teal hover:underline break-all"
                          >
                            {post.link}
                          </a>
                        </div>
                      )}

                      {/* Error Message (for failed posts) */}
                      {post.status === 'failed' && post.errorMessage && (
                        <div>
                          <label className="block text-xs font-medium text-red-500 mb-1 uppercase">Error Reason</label>
                          <div className="bg-red-50 border border-red-200 rounded-lg p-3 text-sm text-red-700">
                            {post.errorMessage}
                          </div>
                        </div>
                      )}

                      {/* Metadata */}
                      <div className="grid grid-cols-2 gap-4 text-sm">
                        <div>
                          <label className="block text-xs font-medium text-gray-500 mb-1 uppercase">Content Type</label>
                          <span className="text-gray-700 capitalize">{post.contentType}</span>
                        </div>
                        <div>
                          <label className="block text-xs font-medium text-gray-500 mb-1 uppercase">Template</label>
                          <span className="text-gray-700">{post.templateName || 'Default / Custom'}</span>
                        </div>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>

      {/* Delete Confirmation Modal */}
      {deleteConfirmId && (
        <div 
          className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"
          onClick={() => setDeleteConfirmId(null)}
        >
          <div 
            className="bg-white rounded-2xl p-6 max-w-sm w-full shadow-xl"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="text-center">
              <div className="w-12 h-12 rounded-full bg-red-100 flex items-center justify-center mx-auto mb-4">
                <Trash2 size={24} className="text-red-600" />
              </div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">Delete Scheduled Post?</h3>
              <p className="text-gray-600 mb-6">
                This will permanently delete this scheduled post. This action cannot be undone.
              </p>
              <div className="flex gap-3">
                <button
                  onClick={() => setDeleteConfirmId(null)}
                  disabled={isDeleting}
                  className="flex-1 px-4 py-2 border border-gray-200 text-gray-700 rounded-lg font-medium hover:bg-gray-50 transition-colors disabled:opacity-50"
                >
                  Cancel
                </button>
                <button
                  onClick={() => handleDelete(deleteConfirmId)}
                  disabled={isDeleting}
                  className="flex-1 px-4 py-2 bg-red-600 text-white rounded-lg font-medium hover:bg-red-700 transition-colors disabled:opacity-50"
                >
                  {isDeleting ? 'Deleting...' : 'Delete'}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
