import mongoose, { Schema, Document, Model } from 'mongoose';

export type ContentType = 'image' | 'video' | 'text' | 'youtube' | 'podcast' | 'article';
export type PostStatus = 'scheduled' | 'processing' | 'sent' | 'failed' | 'cancelled';

export interface IScheduledPost {
  userId: string;
  entityId: string;
  
  // Content details
  contentType: ContentType;
  mediaUrl?: string;
  mediaPublicId?: string;
  message: string;
  link?: string;
  
  // Template tracking
  templateId?: string;
  templateName?: string;
  
  // Scheduling
  scheduledAt: Date;
  scheduledDay: string;
  timeSlotId: string;
  
  // Status tracking
  status: PostStatus;
  sentAt?: Date;
  errorMessage?: string;
  maytapiMessageId?: string;
  
  // Metadata
  priority: number;
  isAutoGenerated: boolean;
  
  createdAt: Date;
  updatedAt: Date;
}

export interface IScheduledPostDocument extends IScheduledPost, Document {}

const ScheduledPostSchema = new Schema<IScheduledPostDocument>(
  {
    userId: { type: String, required: true, index: true },
    entityId: { type: String, required: true, index: true },
    
    contentType: { 
      type: String, 
      enum: ['image', 'video', 'text', 'youtube', 'podcast', 'article'],
      required: true 
    },
    mediaUrl: { type: String },
    mediaPublicId: { type: String },
    message: { type: String, required: true },
    link: { type: String },
    
    templateId: { type: String },
    templateName: { type: String },
    
    scheduledAt: { type: Date, required: true, index: true },
    scheduledDay: { type: String, required: true },
    timeSlotId: { type: String, required: true },
    
    status: { 
      type: String, 
      enum: ['scheduled', 'processing', 'sent', 'failed', 'cancelled'],
      default: 'scheduled',
      index: true
    },
    sentAt: { type: Date },
    errorMessage: { type: String },
    maytapiMessageId: { type: String },
    
    priority: { type: Number, default: 0 },
    isAutoGenerated: { type: Boolean, default: false },
  },
  { timestamps: true }
);

// Indexes for efficient querying
ScheduledPostSchema.index({ userId: 1, scheduledAt: 1, status: 1 });
ScheduledPostSchema.index({ entityId: 1, contentType: 1 });
ScheduledPostSchema.index({ status: 1, scheduledAt: 1 });

export const ScheduledPost: Model<IScheduledPostDocument> =
  mongoose.models.ScheduledPost || 
  mongoose.model<IScheduledPostDocument>('ScheduledPost', ScheduledPostSchema);

